# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npx c8 --reporter=lcovonly mocha
    - run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    - run: ls -lah
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: lcov.info
    - run: ls -lah
